/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiBlogRouteImport } from './routes/api.blog'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiDashboardSubmissionsRouteImport } from './routes/api.dashboard.submissions'
import { Route as ApiDashboardStatsRouteImport } from './routes/api.dashboard.stats'
import { Route as ApiDashboardBlogRouteImport } from './routes/api.dashboard.blog'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthCheckRouteImport } from './routes/api.auth.check'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiDashboardBlogCreateRouteImport } from './routes/api.dashboard.blog.create'
import { Route as ApiDashboardBlogSlugRouteImport } from './routes/api.dashboard.blog.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogRoute = ApiBlogRouteImport.update({
  id: '/api/blog',
  path: '/api/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardSubmissionsRoute = ApiDashboardSubmissionsRouteImport.update({
  id: '/api/dashboard/submissions',
  path: '/api/dashboard/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardBlogRoute = ApiDashboardBlogRouteImport.update({
  id: '/api/dashboard/blog',
  path: '/api/dashboard/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckRoute = ApiAuthCheckRouteImport.update({
  id: '/api/auth/check',
  path: '/api/auth/check',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardBlogCreateRoute = ApiDashboardBlogCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiDashboardBlogRoute,
} as any)
const ApiDashboardBlogSlugRoute = ApiDashboardBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiDashboardBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/blog': typeof ApiBlogRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/blog': typeof BlogIndexRoute
  '/api/auth/check': typeof ApiAuthCheckRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/dashboard/blog': typeof ApiDashboardBlogRouteWithChildren
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/dashboard/submissions': typeof ApiDashboardSubmissionsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/dashboard/blog/$slug': typeof ApiDashboardBlogSlugRoute
  '/api/dashboard/blog/create': typeof ApiDashboardBlogCreateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/blog': typeof ApiBlogRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/blog': typeof BlogIndexRoute
  '/api/auth/check': typeof ApiAuthCheckRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/dashboard/blog': typeof ApiDashboardBlogRouteWithChildren
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/dashboard/submissions': typeof ApiDashboardSubmissionsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/dashboard/blog/$slug': typeof ApiDashboardBlogSlugRoute
  '/api/dashboard/blog/create': typeof ApiDashboardBlogCreateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/blog': typeof ApiBlogRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/check': typeof ApiAuthCheckRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/dashboard/blog': typeof ApiDashboardBlogRouteWithChildren
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/dashboard/submissions': typeof ApiDashboardSubmissionsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/dashboard/blog/$slug': typeof ApiDashboardBlogSlugRoute
  '/api/dashboard/blog/create': typeof ApiDashboardBlogCreateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/api/blog'
    | '/api/contact'
    | '/blog/$slug'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/blog'
    | '/api/auth/check'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/dashboard/blog'
    | '/api/dashboard/stats'
    | '/api/dashboard/submissions'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/dashboard/blog/$slug'
    | '/api/dashboard/blog/create'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/api/blog'
    | '/api/contact'
    | '/blog/$slug'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/blog'
    | '/api/auth/check'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/dashboard/blog'
    | '/api/dashboard/stats'
    | '/api/dashboard/submissions'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/dashboard/blog/$slug'
    | '/api/dashboard/blog/create'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/api/blog'
    | '/api/contact'
    | '/blog/$slug'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/blog/'
    | '/api/auth/check'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/dashboard/blog'
    | '/api/dashboard/stats'
    | '/api/dashboard/submissions'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/dashboard/blog/$slug'
    | '/api/dashboard/blog/create'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiBlogRoute: typeof ApiBlogRoute
  ApiContactRoute: typeof ApiContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthCheckRoute: typeof ApiAuthCheckRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiDashboardBlogRoute: typeof ApiDashboardBlogRouteWithChildren
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiDashboardSubmissionsRoute: typeof ApiDashboardSubmissionsRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog': {
      id: '/api/blog'
      path: '/api/blog'
      fullPath: '/api/blog'
      preLoaderRoute: typeof ApiBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/submissions': {
      id: '/api/dashboard/submissions'
      path: '/api/dashboard/submissions'
      fullPath: '/api/dashboard/submissions'
      preLoaderRoute: typeof ApiDashboardSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/blog': {
      id: '/api/dashboard/blog'
      path: '/api/dashboard/blog'
      fullPath: '/api/dashboard/blog'
      preLoaderRoute: typeof ApiDashboardBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/check': {
      id: '/api/auth/check'
      path: '/api/auth/check'
      fullPath: '/api/auth/check'
      preLoaderRoute: typeof ApiAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/blog/create': {
      id: '/api/dashboard/blog/create'
      path: '/create'
      fullPath: '/api/dashboard/blog/create'
      preLoaderRoute: typeof ApiDashboardBlogCreateRouteImport
      parentRoute: typeof ApiDashboardBlogRoute
    }
    '/api/dashboard/blog/$slug': {
      id: '/api/dashboard/blog/$slug'
      path: '/$slug'
      fullPath: '/api/dashboard/blog/$slug'
      preLoaderRoute: typeof ApiDashboardBlogSlugRouteImport
      parentRoute: typeof ApiDashboardBlogRoute
    }
  }
}

interface ApiDashboardBlogRouteChildren {
  ApiDashboardBlogSlugRoute: typeof ApiDashboardBlogSlugRoute
  ApiDashboardBlogCreateRoute: typeof ApiDashboardBlogCreateRoute
}

const ApiDashboardBlogRouteChildren: ApiDashboardBlogRouteChildren = {
  ApiDashboardBlogSlugRoute: ApiDashboardBlogSlugRoute,
  ApiDashboardBlogCreateRoute: ApiDashboardBlogCreateRoute,
}

const ApiDashboardBlogRouteWithChildren =
  ApiDashboardBlogRoute._addFileChildren(ApiDashboardBlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiBlogRoute: ApiBlogRoute,
  ApiContactRoute: ApiContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthCheckRoute: ApiAuthCheckRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiDashboardBlogRoute: ApiDashboardBlogRouteWithChildren,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiDashboardSubmissionsRoute: ApiDashboardSubmissionsRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
